# https://github.com/moby/moby/issues/30918
# https://github.com/passbolt/passbolt_docker/issues/103
version: "2"
services:
  mysql:
    image: mysql:8.0.15
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
