# https://hub.docker.com/r/neimheadh/phppgadmin
version: "3"
services:
  postgres:
    image: postgres
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  phppgadmin:
    # image: dockage/phppgadmin:latest
    image: neimheadh/phppgadmin
    environment:
      # - PHP_PG_ADMIN_SERVER_HOST=
      # - PHP_PG_ADMIN_SERVER_PORT=5432
      # - PHP_PG_ADMIN_SERVER_DEFAULT_DB=postgres
      # - PHP_PG_ADMIN_MIN_PASSWORD_LENGTH=1
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
    ports:
      - "10080:80"
        #depends_on:
        #- postgres
